config/routes.rb
Rails.application.routes.draw do
  resources :bballs

end

app/models/bball.rb
class Bball < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bballs_controller.rb
class BballsController < ApplicationController
  def index
    @bball = Bball.all
  end
  def show
    @bball = Bball.find(params[:id])
  end
  def new
    @bball = Bball.new
  end
  def create
    Bball.create(bbal_params)
    redirect_to(bball_path)
  end
  def edit
    @bball = Bball.find(params[:id])
  end
  def update 
    @bball = Bball.find(params[:id])
    @bball.update(bball_params)
    redirect_to(bball_path) 
  end
  def destroy
    bball = Bball.find(params[:id])
    bball.destroy
    redirect_to(bball_path)
  end



  private
  def bball_params
    params.require(:bball).permit(:team, :about, :playoff)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bballs/edit.html.erb
<%= form_for @bball do |f| %>
  <%= f.label :team %>
  <%= f.text_field :team %>

  <%= f.label :about %>
  <%= f.text_field :about %>

  <%=f.label :playoff %>
  <%= f.text_field :playoff %>

  <%= f.submit 'Wut U Wearing?' %>


<% end %>

app/views/bballs/index.html.erb
what is up homie
<div class="lost-group">
  <% @bball.each do |bball| %>
  <div vlass = "list-group-item">
    <ul class="ball">
      <li><%= link_to(bball.team, bball_path(bball.id))%></li>
      <li><%= link_to('DELETE', bball_path(bball.id), method: :delete)%></li>
      <li><%= link_to('EDIT', edit_bball_path(bball.id))%></li>
    </ul>
  </div>
  <% end %>
</div>

app/views/bballs/new.html.erb
<%= form_for @bball do |f| %>
  <%= f.label :team %>
  <%= f.text_field :team %>

  <%= f.label :about %>
  <%= f.text_field :about %>

  <%=f.label :playoff %>
  <%= f.text_field :playoff %>

  <%= f.submit 'Wut U Wearing?' %>


<% end %>

app/views/bballs/show.html.erb
<%= params[:id] %>
<%= @bball.team %>
<div class="bball-info">
<%= @bball.about %>
</div>
<%= @bball.playoff %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <li><%= link_to('HOME', bballs_path) %></li>
    <li><%= link_to('New Team', new_bball_path) %></li>
  </nav>

</header>

<%= yield %>

</body>
</html>